# Generated by Django 5.1.6 on 2025-02-27 21:17

import FileManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to=FileManagement.models.define_upload_path, verbose_name='File'),
        ),
    ]
