# Generated by Django 5.1.6 on 2025-02-27 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileManagement', '0002_alter_file_file_attachment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set(),
        ),
    ]
