# Generated by Django 5.1.6 on 2025-02-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileManagement', '0003_alter_file_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AlterField(
            model_name='file',
            name='file_attachment',
            field=models.BinaryField(blank=True, null=True, verbose_name='File'),
        ),
    ]
